import React from "react";

const getSort =
  () =>
  (column, ...args) => {
    return columnDefs
      .find((col) => column.Header === col.Header)
      .sortType(...args);
  };

const sortType = (rowA, rowB, id) => {
  return toInt(rowA.values[id]) > toInt(rowB.values[id]) ? 1 : -1;
};

const textFilter = (rowA, rowB, id) => {
  return rowA.values[id] > rowB.values[id] ? 1 : -1;
};

const toInt = (currency) => Number(currency.replace(/[^0-9.-]+/g, ""));

const columnDefs = [
  {
    Header: "Name",
    accessor: "name",
    sortType: textFilter,
    width: 100,
  },
  {
    Header: "Price",
    accessor: "price",
    sortType,
    width: 75,
  },
  {
    Header: "Monthly Payment",
    accessor: "balloon_payment",
    sortType,
    width: 150,
  },

  {
    Header: "Rebate",
    accessor: "nyr",
    sortType,
    width: 75,
  },
  {
    Header: "Tax Credit",
    accessor: "credit",
    sortType,
    width: 100,
  },
  {
    Header: "Type",
    accessor: "type",
    sortType: textFilter,
    width: 75,
  },
  {
    Header: "Vehicle Type",
    accessor: "vehicle_type",
    sortType: textFilter,
    width: 150,
  },
];

const autos = [
  {
    name: "Chevrolet Bolt",
    price: "$31,500",
    nyr: "$2,000",
    credit: "$0",
    type: "EV",
    vehicle_type: "Sedan",
    payment: "$413",
    balloon: "$4,950",
    balloon_payment: "$359",
  },
  {
    name: "Chevrolet Bolt EUV",
    price: "$33,500",
    nyr: "$2,000",
    credit: "$0",
    type: "EV",
    vehicle_type: "Sedan",
    payment: "$439",
    balloon: "$5,265",
    balloon_payment: "$382",
  },
  {
    name: "Chrysler Pacifica",
    price: "$40,620",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$532",
    balloon: "$8,000",
    balloon_payment: "$445",
  },
  {
    name: "Ford Escape Plug-In Hybrid",
    price: "$33,895",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$444",
    balloon: "$8,000",
    balloon_payment: "$357",
  },
  {
    name: "Ford Fusion Energi",
    price: "$37,000",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "Sedan",
    payment: "$485",
    balloon: "$8,000",
    balloon_payment: "$398",
  },
  {
    name: "Ford Mustang Mach-E",
    price: "$43,895",
    nyr: "$500",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$575",
    balloon: "$8,000",
    balloon_payment: "$488",
  },
  {
    name: "Hyundai Ioniq 5",
    price: "$43,650",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$572",
    balloon: "$9,500",
    balloon_payment: "$469",
  },
  {
    name: "Hyundai Kona Electric",
    price: "$34,000",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$445",
    balloon: "$9,500",
    balloon_payment: "$343",
  },
  {
    name: "Hyundai Santa Fe Plug-In Hybrid",
    price: "$39,500",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$517",
    balloon: "$8,000",
    balloon_payment: "$431",
  },
  {
    name: "Jeep Grand Cherokee 4xe",
    price: "$55,865",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$732",
    balloon: "$8,780",
    balloon_payment: "$637",
  },
  {
    name: "Jeep Wrangler 4xe",
    price: "$53,795",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$705",
    balloon: "$8,454",
    balloon_payment: "$613",
  },
  {
    name: "Kia EV6",
    price: "$40,900",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$536",
    balloon: "$9,500",
    balloon_payment: "$433",
  },
  {
    name: "Kia Niro Electric",
    price: "$39,990",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "Sedan",
    payment: "$524",
    balloon: "$9,500",
    balloon_payment: "$421",
  },
  {
    name: "Lexus NX Plug-In Hybrid",
    price: "$56,725",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$743",
    balloon: "$8,915",
    balloon_payment: "$646",
  },
  {
    name: "Lincoln Aviator Grand Touring",
    price: "$68,680",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$899",
    balloon: "$10,794",
    balloon_payment: "$783",
  },
  {
    name: "Lincoln Corsair Grand Touring",
    price: "$51,595",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$676",
    balloon: "$8,109",
    balloon_payment: "$588",
  },
  {
    name: "Mini Cooper Electric",
    price: "$29,900",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "Sedan",
    payment: "$392",
    balloon: "$9,500",
    balloon_payment: "$289",
  },
  {
    name: "Nissan Leaf",
    price: "$27,400",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "Sedan",
    payment: "$359",
    balloon: "$9,500",
    balloon_payment: "$256",
  },
  {
    name: "Polestar 2",
    price: "$45,900",
    nyr: "$500",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$601",
    balloon: "$8,000",
    balloon_payment: "$515",
  },
  {
    name: "Porsche Taycan",
    price: "$82,700",
    nyr: "$500",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "Sedan",
    payment: "$1,083",
    balloon: "$12,997",
    balloon_payment: "$943",
  },
  {
    name: "Subaru Crosstrek Hybrid",
    price: "$35,845",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$469",
    balloon: "$8,000",
    balloon_payment: "$383",
  },
  {
    name: "Tesla Model 3",
    price: "$43,000",
    nyr: "$500",
    credit: "$0",
    type: "EV",
    vehicle_type: "Sedan",
    payment: "$563",
    balloon: "$6,758",
    balloon_payment: "$490",
  },
  {
    name: "Tesla Model Y",
    price: "$60,000",
    nyr: "$500",
    credit: "$0",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$786",
    balloon: "$9,429",
    balloon_payment: "$684",
  },
  {
    name: "Tesla Model S",
    price: "$100,000",
    nyr: "$500",
    credit: "$0",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$1,310",
    balloon: "$15,716",
    balloon_payment: "$1,140",
  },
  {
    name: "Tesla Model X",
    price: "$115,000",
    nyr: "$500",
    credit: "$0",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$1,506",
    balloon: "$18,073",
    balloon_payment: "$1,311",
  },
  {
    name: "Toyota BZ4X",
    price: "$42,000",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$550",
    balloon: "$9,500",
    balloon_payment: "$447",
  },
  {
    name: "Toyota Prius Prime",
    price: "$28,220",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "Sedan",
    payment: "$370",
    balloon: "$8,000",
    balloon_payment: "$283",
  },
  {
    name: "Toyota RAV4 Prime",
    price: "$39,800",
    nyr: "$1,000",
    credit: "$7,500",
    type: "PHEV",
    vehicle_type: "SUV",
    payment: "$521",
    balloon: "$8,500",
    balloon_payment: "$429",
  },
  {
    name: "Volkswagen ID.4",
    price: "$41,230",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$540",
    balloon: "$9,500",
    balloon_payment: "$437",
  },
  {
    name: "Volvo XC40 Recharge",
    price: "$51,700",
    nyr: "$500",
    credit: "$7,500",
    type: "EV",
    vehicle_type: "SUV",
    payment: "$677",
    balloon: "$8,125",
    balloon_payment: "$589",
  },
];
export { columnDefs, autos, sortType, getSort };
