import React from "react";

const sortType = () => (rowA, rowB, id) => {
  console.log(rowA, rowB);
  return toInt(rowA.values[id]) > toInt(rowB.values[id]) ? 1 : -1;
};

const toInt = (currency) => Number(currency.replace(/[^0-9.-]+/g, ""));

const columnDefs = [
  {
    Header: "Name",
    accessor: "name",
    sortType,
  },
  {
    Header: "Price",
    accessor: "price",
    sortType,
  },
  {
    Header: "Monthly Payment",
    accessor: "balloon_payment",
    sortType,
  },

  {
    Header: "Rebate",
    accessor: "nyr",
    sortType,
  },
  {
    Header: "Tax Credit",
    accessor: "credit",
    sortType,
  },
  {
    Header: "Type",
    accessor: "type",
    sortType,
  },
];

const autos = [
  {
    name: "Chevrolet Bolt",
    price: "$31,500",
    nyr: "$2,000",
    credit: "$0",
    type: "EV",
    payment: "$475",
    "": "",
    balloon: "$5,699",
    balloon_payment: "$402",
  },
  {
    name: "Chevrolet Bolt EUV",
    price: "$33,500",
    nyr: "$2,000",
    credit: "$0",
    type: "EV",
    payment: "$505",
    "": "",
    balloon: "$6,061",
    balloon_payment: "$428",
  },
  {
    name: "Chrysler Pacifica",
    price: "$40,620",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$612",
    "": "",
    balloon: "$8,000",
    balloon_payment: "$510",
  },
  {
    name: "Ford Escape Plug-In Hybrid",
    price: "$33,895",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$511",
    "": "",
    balloon: "$8,000",
    balloon_payment: "$409",
  },
  {
    name: "Ford Fusion Energi",
    price: "$37,000",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$558",
    "": "",
    balloon: "$8,000",
    balloon_payment: "$456",
  },
  {
    name: "Ford Mustang Mach-E",
    price: "$43,895",
    nyr: "$500",
    credit: "$7,500",
    type: "EV",
    payment: "$662",
    "": "",
    balloon: "$8,000",
    balloon_payment: "$559",
  },
  {
    name: "Hyundai Ioniq 5",
    price: "$43,650",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    payment: "$658",
    "": "",
    balloon: "$9,500",
    balloon_payment: "$537",
  },
  {
    name: "Hyundai Kona Electric",
    price: "$34,000",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    payment: "$513",
    "": "",
    balloon: "$9,500",
    balloon_payment: "$391",
  },
  {
    name: "Hyundai Santa Fe Plug-In Hybrid",
    price: "$39,500",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$596",
    "": "",
    balloon: "$8,000",
    balloon_payment: "$493",
  },
  {
    name: "Jeep Grand Cherokee 4xe",
    price: "$55,865",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$842",
    "": "",
    balloon: "$10,108",
    balloon_payment: "$713",
  },
  {
    name: "Jeep Wrangler 4xe",
    price: "$53,795",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$811",
    "": "",
    balloon: "$9,733",
    balloon_payment: "$687",
  },
  {
    name: "Kia EV6",
    price: "$40,900",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    payment: "$617",
    "": "",
    balloon: "$9,500",
    balloon_payment: "$495",
  },
  {
    name: "Kia Niro Electric",
    price: "$39,990",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    payment: "$603",
    "": "",
    balloon: "$9,500",
    balloon_payment: "$481",
  },
  {
    name: "Lexus NX Plug-In Hybrid",
    price: "$56,725",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$855",
    "": "",
    balloon: "$10,263",
    balloon_payment: "$724",
  },
  {
    name: "Lincoln Aviator Grand Touring",
    price: "$68,680",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$1,036",
    "": "",
    balloon: "$12,426",
    balloon_payment: "$877",
  },
  {
    name: "Lincoln Corsair Grand Touring",
    price: "$51,595",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$778",
    "": "",
    balloon: "$9,335",
    balloon_payment: "$658",
  },
  {
    name: "Nissan Leaf",
    price: "$27,400",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    payment: "$413",
    "": "",
    balloon: "$9,500",
    balloon_payment: "$292",
  },
  {
    name: "Porsche Taycan",
    price: "$82,700",
    nyr: "$500",
    credit: "$7,500",
    type: "EV",
    payment: "$1,247",
    "": "",
    balloon: "$14,963",
    balloon_payment: "$1,055",
  },
  {
    name: "Subaru Crosstrek Hybrid",
    price: "$35,845",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$540",
    "": "",
    balloon: "$8,000",
    balloon_payment: "$438",
  },
  {
    name: "Toyota Prius Prime",
    price: "$28,220",
    nyr: "$500",
    credit: "$7,500",
    type: "PHEV",
    payment: "$425",
    "": "",
    balloon: "$8,000",
    balloon_payment: "$323",
  },
  {
    name: "Toyota RAV4 Prime",
    price: "$39,800",
    nyr: "$1,000",
    credit: "$7,500",
    type: "PHEV",
    payment: "$600",
    "": "",
    balloon: "$8,500",
    balloon_payment: "$491",
  },
  {
    name: "Volkswagen ID.4",
    price: "$41,230",
    nyr: "$2,000",
    credit: "$7,500",
    type: "EV",
    payment: "$622",
    "": "",
    balloon: "$9,500",
    balloon_payment: "$500",
  },
  {
    name: "Volvo XC40 Recharge",
    price: "$51,700",
    nyr: "$500",
    credit: "$7,500",
    type: "EV",
    payment: "$780",
    "": "",
    balloon: "$9,354",
    balloon_payment: "$660",
  },
];
export { columnDefs, autos, sortType };
